---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)

library(flexdashboard)
```


```{r import data}
data("instacart")
instacart = 
  instacart |> 
  filter(
    department %in% c("produce", "frozen", "snacks",
                      "dairy","bakery","beverages","household"),
    order_hour_of_day %in% c(6:9, 12:14, 18:21)) |> 
  mutate(
    time_of_day = case_when(
      order_hour_of_day %in% 6:9 ~ "Morning",
      order_hour_of_day %in% 12:14 ~ "Afternoon",
      order_hour_of_day %in% 18:21 ~ "Evening")) |> 
  select(
    user_id, order_id, product_name, aisle, department,
    order_hour_of_day, add_to_cart_order, reordered, time_of_day
  ) |> 
  sample_n(5000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Plotly Scatterplot

```{r}
instacart |> mutate(
    text_label = str_c("Product: ", product_name, 
                       "\nDepartment: ", department, 
                       "\nHour of Day: ", order_hour_of_day)) |> 
  plot_ly(
    x = ~order_hour_of_day, 
    y = ~add_to_cart_order, 
    type = "scatter", 
    mode = "markers",
    color = ~department,
    colors = "Paired",
    text = ~text_label) |> 
  layout(
    title = "Instacart Purchases by Time and Cart Position",
    xaxis = list(title = "Order Time (hour)"),
    yaxis = list(title = "Add to Cart Order"),
    margin = list(t = 80) 
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Plotly Pie

```{r}
instacart |> 
  count(department) |>
  plot_ly(
    labels = ~department, 
    values = ~n, 
    type = "pie", 
    textinfo = "label+percent", 
    textposition = "outside",
    marker = list(colors = RColorBrewer::brewer.pal(n = 8, name = "Paired"))
  ) |> 
  layout(
    title = "Order Proportion by Department",
    margin = list(t = 50, b = 50, l = 50, r = 50)
  )
```

### Plotly bar plot

```{r}
instacart |> 
  group_by(department, time_of_day) |> 
  summarise(reorder_rate = mean(reordered), .groups = "drop") |> 
  plot_ly(
    x = ~time_of_day, 
    y = ~reorder_rate, 
    color = ~department,
    type = "bar", 
    colors = "Paired"
  ) |> 
  layout(
    title = "Reorder Rate by Department and Time of Day",
    yaxis = list(title = "Reorder Rate"),
    xaxis = list(title = "Time of Day"),
    barmode = "group",
    margin = list(t = 80) 
  )
```

